repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
        args:
          - ./cmd/auth/main.go
      - id: go-mod-tidy
        args:
          - ./cmd/auth/main.go
      - id: go-unit-tests
  - repo: https://github.com/m-v-kalashnikov/pre-commit-hooks
    rev: v0.1.0
    hooks:
      - id: go-vet
        args:
          - ./cmd/auth/main.go
